# Generated by Django 4.1.7 on 2023-03-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptsJs',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('script', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpyLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField(blank=True, null=True)),
                ('localstorage', models.TextField(blank=True, null=True)),
                ('cookies', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
