# Generated by Django 4.1.7 on 2023-03-04 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spylogs',
            name='insert_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scriptsjs',
            name='script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
