# Generated by Django 4.1.7 on 2023-03-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0003_rename_scriptsjs_scripts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpyLogs',
            new_name='Logs',
        ),
    ]
